export const MAX_INBOUND_BODY_BYTES = 32 * 1024;
export const MAX_INBOUND_MESSAGE_LENGTH = 8_000;

export const MAX_EXTRACTED_MONEY = 1_000_000_000_000;
export const MAX_EXTRACTED_UNITS = 10_000;
export const MAX_EXTRACTED_TEXT_LENGTH = 2_000;
export const MAX_EXTRACTED_SIGNAL_ITEMS = 20;

export const MAX_STORED_LEAD_SIGNAL_ITEMS = 100;
export const MAX_RECENT_LLM_MESSAGES = 3;
export const MAX_RECENT_LLM_MESSAGE_LENGTH = 2_000;

export const MAX_INCOMING_PROCESSING_ATTEMPTS = 3;
